language: bash
services: docker

env:
  global:
    - OPENCV_VERSION=3.1.0
  matrix:
    - PYTHON_VERSION=3
    - PYTHON_VERSION=3.5
    - PYTHON_VERSION=2.7

before_script:
  - env | sort
  - image="mvonrohr/opencv:$OPENCV_VERSION-python-$PYTHON_VERSION"

script:
  - docker build --build-arg OPENCV_VERSION=$OPENCV_VERSION --build-arg PYTHON_VERSION=$PYTHON_VERSION -t "$image" .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$image"

after_script:
  - docker images
